package com.hm.pharmacy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomersAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomersAllPropertiesEquals(Customers expected, Customers actual) {
        assertCustomersAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomersAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomersAllUpdatablePropertiesEquals(Customers expected, Customers actual) {
        assertCustomersUpdatableFieldsEquals(expected, actual);
        assertCustomersUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomersAutoGeneratedPropertiesEquals(Customers expected, Customers actual) {
        assertThat(actual)
            .as("Verify Customers auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomersUpdatableFieldsEquals(Customers expected, Customers actual) {
        assertThat(actual)
            .as("Verify Customers relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomersUpdatableRelationshipsEquals(Customers expected, Customers actual) {
        // empty method
    }
}
