package com.hm.pharmacy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicineBatchesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineBatchesAllPropertiesEquals(MedicineBatches expected, MedicineBatches actual) {
        assertMedicineBatchesAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicineBatchesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineBatchesAllUpdatablePropertiesEquals(MedicineBatches expected, MedicineBatches actual) {
        assertMedicineBatchesUpdatableFieldsEquals(expected, actual);
        assertMedicineBatchesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineBatchesAutoGeneratedPropertiesEquals(MedicineBatches expected, MedicineBatches actual) {
        assertThat(actual)
            .as("Verify MedicineBatches auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineBatchesUpdatableFieldsEquals(MedicineBatches expected, MedicineBatches actual) {
        assertThat(actual)
            .as("Verify MedicineBatches relevant properties")
            .satisfies(a -> assertThat(a.getBatchNumber()).as("check batchNumber").isEqualTo(expected.getBatchNumber()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineBatchesUpdatableRelationshipsEquals(MedicineBatches expected, MedicineBatches actual) {
        assertThat(actual)
            .as("Verify MedicineBatches relationships")
            .satisfies(a -> assertThat(a.getPurchases()).as("check purchases").isEqualTo(expected.getPurchases()))
            .satisfies(a -> assertThat(a.getMedicines()).as("check medicines").isEqualTo(expected.getMedicines()));
    }
}
