package com.hm.pharmacy.domain;

import static com.hm.pharmacy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MedicinesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicinesAllPropertiesEquals(Medicines expected, Medicines actual) {
        assertMedicinesAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicinesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicinesAllUpdatablePropertiesEquals(Medicines expected, Medicines actual) {
        assertMedicinesUpdatableFieldsEquals(expected, actual);
        assertMedicinesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicinesAutoGeneratedPropertiesEquals(Medicines expected, Medicines actual) {
        assertThat(actual)
            .as("Verify Medicines auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicinesUpdatableFieldsEquals(Medicines expected, Medicines actual) {
        assertThat(actual)
            .as("Verify Medicines relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getManufacturer()).as("check manufacturer").isEqualTo(expected.getManufacturer()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getStock()).as("check stock").isEqualTo(expected.getStock()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicinesUpdatableRelationshipsEquals(Medicines expected, Medicines actual) {
        // empty method
    }
}
