package com.hm.pharmacy.domain;

import static com.hm.pharmacy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PaymentsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentsAllPropertiesEquals(Payments expected, Payments actual) {
        assertPaymentsAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentsAllUpdatablePropertiesEquals(Payments expected, Payments actual) {
        assertPaymentsUpdatableFieldsEquals(expected, actual);
        assertPaymentsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentsAutoGeneratedPropertiesEquals(Payments expected, Payments actual) {
        assertThat(actual)
            .as("Verify Payments auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentsUpdatableFieldsEquals(Payments expected, Payments actual) {
        assertThat(actual)
            .as("Verify Payments relevant properties")
            .satisfies(a -> assertThat(a.getPaymentDate()).as("check paymentDate").isEqualTo(expected.getPaymentDate()))
            .satisfies(a -> assertThat(a.getPaymentMethod()).as("check paymentMethod").isEqualTo(expected.getPaymentMethod()))
            .satisfies(a -> assertThat(a.getPaymentStatus()).as("check paymentStatus").isEqualTo(expected.getPaymentStatus()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentsUpdatableRelationshipsEquals(Payments expected, Payments actual) {
        assertThat(actual)
            .as("Verify Payments relationships")
            .satisfies(a -> assertThat(a.getSales()).as("check sales").isEqualTo(expected.getSales()));
    }
}
