package com.hm.pharmacy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrescriptionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionsAllPropertiesEquals(Prescriptions expected, Prescriptions actual) {
        assertPrescriptionsAutoGeneratedPropertiesEquals(expected, actual);
        assertPrescriptionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionsAllUpdatablePropertiesEquals(Prescriptions expected, Prescriptions actual) {
        assertPrescriptionsUpdatableFieldsEquals(expected, actual);
        assertPrescriptionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionsAutoGeneratedPropertiesEquals(Prescriptions expected, Prescriptions actual) {
        assertThat(actual)
            .as("Verify Prescriptions auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionsUpdatableFieldsEquals(Prescriptions expected, Prescriptions actual) {
        assertThat(actual)
            .as("Verify Prescriptions relevant properties")
            .satisfies(a -> assertThat(a.getDoctorName()).as("check doctorName").isEqualTo(expected.getDoctorName()))
            .satisfies(a -> assertThat(a.getPrescriptionDate()).as("check prescriptionDate").isEqualTo(expected.getPrescriptionDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrescriptionsUpdatableRelationshipsEquals(Prescriptions expected, Prescriptions actual) {
        assertThat(actual)
            .as("Verify Prescriptions relationships")
            .satisfies(a -> assertThat(a.getCustomers()).as("check customers").isEqualTo(expected.getCustomers()));
    }
}
