package com.hm.pharmacy.domain;

import static com.hm.pharmacy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PurchaseItemsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseItemsAllPropertiesEquals(PurchaseItems expected, PurchaseItems actual) {
        assertPurchaseItemsAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchaseItemsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseItemsAllUpdatablePropertiesEquals(PurchaseItems expected, PurchaseItems actual) {
        assertPurchaseItemsUpdatableFieldsEquals(expected, actual);
        assertPurchaseItemsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseItemsAutoGeneratedPropertiesEquals(PurchaseItems expected, PurchaseItems actual) {
        assertThat(actual)
            .as("Verify PurchaseItems auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseItemsUpdatableFieldsEquals(PurchaseItems expected, PurchaseItems actual) {
        assertThat(actual)
            .as("Verify PurchaseItems relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchaseItemsUpdatableRelationshipsEquals(PurchaseItems expected, PurchaseItems actual) {
        assertThat(actual)
            .as("Verify PurchaseItems relationships")
            .satisfies(a -> assertThat(a.getPurchases()).as("check purchases").isEqualTo(expected.getPurchases()))
            .satisfies(a -> assertThat(a.getMedicines()).as("check medicines").isEqualTo(expected.getMedicines()));
    }
}
