package com.hm.pharmacy.domain;

import static com.hm.pharmacy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PurchasesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasesAllPropertiesEquals(Purchases expected, Purchases actual) {
        assertPurchasesAutoGeneratedPropertiesEquals(expected, actual);
        assertPurchasesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasesAllUpdatablePropertiesEquals(Purchases expected, Purchases actual) {
        assertPurchasesUpdatableFieldsEquals(expected, actual);
        assertPurchasesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasesAutoGeneratedPropertiesEquals(Purchases expected, Purchases actual) {
        assertThat(actual)
            .as("Verify Purchases auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasesUpdatableFieldsEquals(Purchases expected, Purchases actual) {
        assertThat(actual)
            .as("Verify Purchases relevant properties")
            .satisfies(a -> assertThat(a.getPurchaseDate()).as("check purchaseDate").isEqualTo(expected.getPurchaseDate()))
            .satisfies(a -> assertThat(a.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(expected.getInvoiceNumber()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPurchasesUpdatableRelationshipsEquals(Purchases expected, Purchases actual) {
        assertThat(actual)
            .as("Verify Purchases relationships")
            .satisfies(a -> assertThat(a.getSuppliers()).as("check suppliers").isEqualTo(expected.getSuppliers()));
    }
}
