package com.hm.pharmacy.domain;

import static com.hm.pharmacy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaleItemsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleItemsAllPropertiesEquals(SaleItems expected, SaleItems actual) {
        assertSaleItemsAutoGeneratedPropertiesEquals(expected, actual);
        assertSaleItemsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleItemsAllUpdatablePropertiesEquals(SaleItems expected, SaleItems actual) {
        assertSaleItemsUpdatableFieldsEquals(expected, actual);
        assertSaleItemsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleItemsAutoGeneratedPropertiesEquals(SaleItems expected, SaleItems actual) {
        assertThat(actual)
            .as("Verify SaleItems auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleItemsUpdatableFieldsEquals(SaleItems expected, SaleItems actual) {
        assertThat(actual)
            .as("Verify SaleItems relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleItemsUpdatableRelationshipsEquals(SaleItems expected, SaleItems actual) {
        assertThat(actual)
            .as("Verify SaleItems relationships")
            .satisfies(a -> assertThat(a.getMedicines()).as("check medicines").isEqualTo(expected.getMedicines()))
            .satisfies(a -> assertThat(a.getSales()).as("check sales").isEqualTo(expected.getSales()));
    }
}
