package com.hm.pharmacy.domain;

import static com.hm.pharmacy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SalesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesAllPropertiesEquals(Sales expected, Sales actual) {
        assertSalesAutoGeneratedPropertiesEquals(expected, actual);
        assertSalesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesAllUpdatablePropertiesEquals(Sales expected, Sales actual) {
        assertSalesUpdatableFieldsEquals(expected, actual);
        assertSalesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesAutoGeneratedPropertiesEquals(Sales expected, Sales actual) {
        assertThat(actual)
            .as("Verify Sales auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesUpdatableFieldsEquals(Sales expected, Sales actual) {
        assertThat(actual)
            .as("Verify Sales relevant properties")
            .satisfies(a -> assertThat(a.getSaleDate()).as("check saleDate").isEqualTo(expected.getSaleDate()))
            .satisfies(a -> assertThat(a.getInvoiceNumber()).as("check invoiceNumber").isEqualTo(expected.getInvoiceNumber()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesUpdatableRelationshipsEquals(Sales expected, Sales actual) {
        assertThat(actual)
            .as("Verify Sales relationships")
            .satisfies(a -> assertThat(a.getCustomers()).as("check customers").isEqualTo(expected.getCustomers()));
    }
}
