package com.hm.pharmacy.domain;

import static com.hm.pharmacy.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SupplierPaymentsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierPaymentsAllPropertiesEquals(SupplierPayments expected, SupplierPayments actual) {
        assertSupplierPaymentsAutoGeneratedPropertiesEquals(expected, actual);
        assertSupplierPaymentsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierPaymentsAllUpdatablePropertiesEquals(SupplierPayments expected, SupplierPayments actual) {
        assertSupplierPaymentsUpdatableFieldsEquals(expected, actual);
        assertSupplierPaymentsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierPaymentsAutoGeneratedPropertiesEquals(SupplierPayments expected, SupplierPayments actual) {
        assertThat(actual)
            .as("Verify SupplierPayments auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierPaymentsUpdatableFieldsEquals(SupplierPayments expected, SupplierPayments actual) {
        assertThat(actual)
            .as("Verify SupplierPayments relevant properties")
            .satisfies(a -> assertThat(a.getPaymentDate()).as("check paymentDate").isEqualTo(expected.getPaymentDate()))
            .satisfies(a -> assertThat(a.getPaymentMethod()).as("check paymentMethod").isEqualTo(expected.getPaymentMethod()))
            .satisfies(a -> assertThat(a.getPaymentStatus()).as("check paymentStatus").isEqualTo(expected.getPaymentStatus()))
            .satisfies(a ->
                assertThat(a.getAmountPaid())
                    .as("check amountPaid")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountPaid())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierPaymentsUpdatableRelationshipsEquals(SupplierPayments expected, SupplierPayments actual) {
        assertThat(actual)
            .as("Verify SupplierPayments relationships")
            .satisfies(a -> assertThat(a.getSuppliers()).as("check suppliers").isEqualTo(expected.getSuppliers()))
            .satisfies(a -> assertThat(a.getPurchases()).as("check purchases").isEqualTo(expected.getPurchases()));
    }
}
