package com.hm.pharmacy.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SuppliersAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuppliersAllPropertiesEquals(Suppliers expected, Suppliers actual) {
        assertSuppliersAutoGeneratedPropertiesEquals(expected, actual);
        assertSuppliersAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuppliersAllUpdatablePropertiesEquals(Suppliers expected, Suppliers actual) {
        assertSuppliersUpdatableFieldsEquals(expected, actual);
        assertSuppliersUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuppliersAutoGeneratedPropertiesEquals(Suppliers expected, Suppliers actual) {
        assertThat(actual)
            .as("Verify Suppliers auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuppliersUpdatableFieldsEquals(Suppliers expected, Suppliers actual) {
        assertThat(actual)
            .as("Verify Suppliers relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getContactPerson()).as("check contactPerson").isEqualTo(expected.getContactPerson()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuppliersUpdatableRelationshipsEquals(Suppliers expected, Suppliers actual) {
        // empty method
    }
}
